#!/usr/bin/env python
from distutils.core import setup

setup(name="recognition",
      version="0.1",
      description="pattern recognition for passwords",
      author="ssem",
      packages=['rec'],
      required=['pyenchant'],
      scripts=['bin/parse_add_basewords',
               'bin/parse_all',
               'bin/parse_basewords',
               'bin/parse_chars',
               'bin/parse_complexity',
               'bin/parse_entropy',
               'bin/parse_lengths',
               'bin/parse_lengths',
               'bin/parse_mods',
               'bin/parse_patterns',
               'bin/parse_prefixes',
               'bin/parse_sets',
               'bin/parse_suffixes',
               'bin/parse_time_and_patterns',
               'bin/parse_top_passwords',
               'bin/parse_years'])
