#!/usr/bin/env python

import requests

http = requests.get('http://www.listchallenges.com/100-popular-candies')
for x in http.content.split('div'):
    if 'class="itemName">' in x:
        for i in x.split('\t'):
            if '\r\n' in i and 'class="itemName"' not in i and len(i) > 2:
                print i.replace('\r\n', '')

