#!/usr/bin/env python
import sys
import argparse


def addition(fname):
    last = 0
    for line in open(fname, 'r'):
        line = line.rstrip('\r\n')
        for x in xrange(len(line)):
            last = ((ord(line[x]) + last - 32) % 95) + 32
            sys.stdout.write(chr(last))
        print

if __name__ == '__main__':
    parse = argparse.ArgumentParser()
    parse.add_argument('file', help="file to modify")
    args = parse.parse_args()
    addition(args.file)
