#!/usr/bin/env python
import sys

class Lower:
    def from_stdin(self):
        for line in sys.stdin:
            print line.lower().rstrip('\r\n')

    def from_file(self, word_list):
        f = open(word_list, 'r')
        for line in f:
            print line.lower().rstrip('\r\n')
        f.close()

if __name__ == '__main__':
    try:
        lower = Lower()
        if sys.argv[1] == '-i':
            lower.from_stdin()
        else:
            lower.from_file(sys.argv[1])
    except IndexError:
        print '\n\tUsage: lower  -i'
        print '\tUsage: lower < word list >'
        print '\n\tDescription: This program takes in a word list or'
        print '\t\t     reads from stdin and converts each line'
        print '\t\t     to lower case then prints it to the terminal\n'

