#!/usr/bin/env python
import sys

class Prune_List:
    def __init__(self, p_list):
        self._prune(p_list)

    def _prune(self, p_list):
        f = open(p_list, 'r')
        for line in f:
            line = line.rstrip('~`!@#$%^, .?/;:\'"|{}[]()*&\r\n-_=+')
            line = line.lstrip('~`!@#$%^, .?/;:\'"|{}[]()*&\r\n-_=+')
            line = line.replace('\t', '')
            line = line.replace('   ', '')
            if len(line) > 2:
                print line.lower()

if __name__ == '__main__':
    try:
        prune_list  = Prune_List(sys.argv[1])
    except IndexError:
        print '\n\tUsage prune_list   < password list >\n'

