#!/usr/bin/env python
import sys
import argparse


def rot(keys, fname):
    for line in open(fname, 'r'):
        line = line.rstrip('\r\n')
        for x in xrange(len(line)):
            sys.stdout.write(chr(((ord(line[x]) + int(keys[x % len(keys)]) - 32) % 95) + 32))
        print

if __name__ == '__main__':
    parse = argparse.ArgumentParser()
    parse.add_argument('file', help="file to modify")
    parse.add_argument('-d', help="digit to rot by")
    parse.add_argument('-l', help="comma superated list of digits to rot by")
    args = parse.parse_args()
    if args.d:
        rot(args.d, args.file)
    elif args.l:
        rot(args.l.split(','), args.file)
    else:
        print '\n\tno mod selected\n'
