#!/usr/bin/env python
import sys
import argparse
import string


def tabula(fname):
    for line in open(fname, 'r'):
        line = line.rstrip('\r\n')
        try:
            for x in xrange(len(line)):
                sys.stdout.write(string.ascii_uppercase[
                    (1 + x + string.ascii_uppercase.index(line[x].upper())) % 26])
            print
        except ValueError:
            pass # invalid chars in line

if __name__ == '__main__':
    parse = argparse.ArgumentParser()
    parse.add_argument('file', help="file to modify")
    args = parse.parse_args()
    tabula(args.file)
