#!/usr/bin/env python
import sys

class Upper:
    def from_stdin(self):
        for line in sys.stdin:
            print line.upper().rstrip('\r\n')

    def from_file(self, word_list):
        f = open(word_list, 'r')
        for line in f:
            print line.upper().rstrip('\r\n')
        f.close()

if __name__ == '__main__':
    try:
        upper = Upper()
        if sys.argv[1] == '-i':
            upper.from_stdin()
        else:
            upper.from_file(sys.argv[1])
    except IndexError:
        print '\n\tUsage: upper  -i'
        print '\tUsage: upper < word list >'
        print '\n\tDescription: This program takes in a word list or'
        print '\t\t     reads from stdin and converts each line'
        print '\t\t     to lower case then prints it to the terminal\n'

